export const Colors = {
  primary: '#ba002b',
  primaryContainer: '#e5183b',
  secondary: '#ab323b',
  secondaryContainer: '#ff7075',
  tertiary: '#00685c',
  surface: '#f9f9fb',
  surfaceDim: '#d9dadc',
  surfaceContainerLowest: '#ffffff',
  surfaceContainerLow: '#f3f3f5',
  surfaceContainer: '#eeeef0',
  surfaceContainerHigh: '#e8e8ea',
  surfaceContainerHighest: '#e2e2e4',
  onSurface: '#1a1c1d',
  onSurfaceVariant: '#5d3f3f',
  onPrimary: '#ffffff',
  outline: '#916e6e',
  outlineVariant: '#e6bdbc',
} as const
