############################
# Application
############################
quarkus.application.name=groupys-backend
quarkus.http.root-path=/api
quarkus.http.host=0.0.0.0

############################
# CORS (dev-friendly)
############################
quarkus.http.cors.enabled=true
quarkus.http.cors.origins=${APP_CORS_ORIGINS:http://localhost:3000,http://localhost:8081,http://localhost:19006}
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.headers=accept,authorization,content-type,x-requested-with
quarkus.http.cors.exposed-headers=location,link
quarkus.http.cors.access-control-max-age=24H
# %prod.quarkus.http.cors.origins=${APP_CORS_ORIGINS:https://what-to-wear.cms-building.at}

############################
# MinIO (quarkus-minio)
############################
# Disable Dev Services explicitly
quarkus.minio.devservices.enabled=false

# Connection
quarkus.minio.url=http://localhost:9000
quarkus.minio.region=eu-central-1
quarkus.minio.host=localhost
quarkus.minio.port=9000
quarkus.minio.secure=false
# Credentials (use env vars!)
quarkus.minio.access-key=${MINIO_ACCESS_KEY:admin}
quarkus.minio.secret-key=${MINIO_SECRET_KEY:admin123}

############################
# PostgreSQL
############################
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/db
quarkus.datasource.username=${DB_USER:app}
quarkus.datasource.password=${DB_PASS:app}

# Hibernate ORM
%test.quarkus.hibernate-orm.schema-management.strategy=drop-and-create
%dev.quarkus.hibernate-orm.schema-management.strategy=update
%prod.quarkus.hibernate-orm.schema-management.strategy=validate

quarkus.datasource.devservices.enabled=false
%dev.quarkus.hibernate-orm.log.sql=true
%test.quarkus.hibernate-orm.log.sql=true
%prod.quarkus.http.access-log.enabled=true

############################
# Deezer REST Client
############################
quarkus.rest-client.deezer-api.url=https://api.deezer.com
quarkus.rest-client.deezer-api.scope=jakarta.inject.Singleton

############################
# Last.FM REST Client
############################
quarkus.rest-client.lastfm-api.url=https://ws.audioscrobbler.com/2.0/
quarkus.rest-client.lastfm-api.scope=jakarta.inject.Singleton
lastfm.api.key=${LASTFM_API_KEY:6b3434e6393f43fd45b57dd271eda966}
